name: you
description: What internet knows about you
version: 1.0.1+2
environment:
  sdk: ">=2.17.1 <3.16.9"

dependencies:
  flutter:
    sdk: flutter

  animated_background:
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  share_plus: ^4.0.10+1
  flutter_walkthrough_screen: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/

  fonts:
    - family: Acme
      fonts:
       
        - asset: assets/font/Acme-Regular.ttf
          weight: 600
    - family: Josefin Sans
      fonts:
        - asset: assets/font/JosefinSans-Regular.ttf 
          weight: 200   
    
